spring.application.name=SimplyFly

#DB Settings
spring.datasource.url=jdbc:mysql://localhost:3306/simplyfly?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=talhapatel123

#Hibernate Settings
spring.jpa.hibernate.ddl-auto=update